create table "public"."week" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "start_date" date,
    "end_date" date,
    "status" text
);


alter table "public"."week" enable row level security;

CREATE UNIQUE INDEX week_pkey ON public.week USING btree (id);

alter table "public"."week" add constraint "week_pkey" PRIMARY KEY using index "week_pkey";

grant delete on table "public"."week" to "anon";

grant insert on table "public"."week" to "anon";

grant references on table "public"."week" to "anon";

grant select on table "public"."week" to "anon";

grant trigger on table "public"."week" to "anon";

grant truncate on table "public"."week" to "anon";

grant update on table "public"."week" to "anon";

grant delete on table "public"."week" to "authenticated";

grant insert on table "public"."week" to "authenticated";

grant references on table "public"."week" to "authenticated";

grant select on table "public"."week" to "authenticated";

grant trigger on table "public"."week" to "authenticated";

grant truncate on table "public"."week" to "authenticated";

grant update on table "public"."week" to "authenticated";

grant delete on table "public"."week" to "service_role";

grant insert on table "public"."week" to "service_role";

grant references on table "public"."week" to "service_role";

grant select on table "public"."week" to "service_role";

grant trigger on table "public"."week" to "service_role";

grant truncate on table "public"."week" to "service_role";

grant update on table "public"."week" to "service_role";


